### ISSUE TITLE
Consolidated list of all ENV variables

### ISSUE THREAD

**Issue by tleish** [anycable/docs.anycable.io#47]
We are in the process of upgrading AnyCable.  With the renaming of multiple ENV variables, it took more time than it probably should have trying to find and locate all changes through the documentation.  It would help if listed on the upgrade docs (it looks like some of them were missed).  I knew the setting I wanted to use, but it took time to track down the correct ENV variable name.  I'd search both the docs.anycable.io, this repo, the repo's of other AnyCable github projects.  Searching didn't work as I'd hoped.

One idea, create a consolidated list/dictionary of ENV variables.  This page could also link to existing pages that give more explanation on why/how the ENV variables are used.

BTW, even with this "complaint"... the docs are pretty comprehensive overall.

**Comment by palkan** [comment]
> create a consolidated list/dictionary of ENV variables

For AnyCable server, you can run `anycable-go -h` and see all the ENV variables. For Ruby, running `bundle exec anycable -h` does about the same (though some non-CLI options are missing from there, so calling `pp AnyCable.config` gives the full configuration schema information).

**Comment by tleish** [comment]
Ah, wish I would've tried this earlier.  Thanks.
